//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_CHRYSALLIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipus_events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipus_events()
        {
            this.esdeveniments = new HashSet<esdeveniments>();
        }
    
        public int idTipus { get; set; }
        public string nom { get; set; }
        public string imatge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<esdeveniments> esdeveniments { get; set; }
    }
}
